Inventory.Web/Controllers/Register/RegisterProductController.cs
using Inventory.Web.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Inventory.Web.Controllers.Register
{
    [Authorize(Roles = "Administrator, Operator")]
    public class RegisterProductController : BaseController
    {
        private const int _quantMaxLinesPerPage = 5;
        private const int ActualPage = 1;


        public ActionResult Index()
        {
            ViewBag.ListLenPage = new SelectList(new int[] { _quantMaxLinesPerPage, 10, 15, 20 }, _quantMaxLinesPerPage);
            ViewBag.QuantMaxLinesPerPage = _quantMaxLinesPerPage;
            ViewBag.ActualPage = 1;

            //var list = Mapper.Map<List<ProductViewModel>>(ProductModel.RescueList(ViewBag.ActualPage, _quantMaxLinesPerPage));
            var list = Mapper.Map<List<ProductViewModel>>(ProductModel.RescueList(ActualPage, _quantMaxLinesPerPage));
            var quant = ProductModel.RescueQuantity();

            var difQuantPages = (quant % ViewBag.QuantMaxLinesPerPage) > 0 ? 1 : 0;
            ViewBag.QuantPages = (quant / ViewBag.QuantMaxLinesPerPage) + difQuantPages;
            ViewBag.UnitsMeasure = Mapper.Map<List<UnitMeasureViewModel>>(UnitMeasureModel.RescueList(1,9999));
            ViewBag.Groups = Mapper.Map<List<GroupProductViewModel>>(GroupProductModel.RescueList(1, 9999));
            ViewBag.Brands = Mapper.Map<List<ProductBrandViewModel>>(ProductBrandModel.RescueList(1, 9999));
            ViewBag.Providers = Mapper.Map<List<ProviderViewModel>>(ProviderModel.RescueList(1, 9999)); //nao deveria ter nada dentro dos paranteses
            ViewBag.StorageLocations = Mapper.Map<List<StorageLocationViewModel>>(StorageLocationModel.RescueList(1, 9999));

            return View(list);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult ProductPage(int page, int lenPage, string filter, string order)
        {
            var list = Mapper.Map<List<ProductViewModel>>(ProductModel.RescueList(page, lenPage, filter, order));

            return Json(list);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult RescueProduct(int id)
        {
            var vm = Mapper.Map<ProductViewModel>(ProductModel.IdRescue(id));
            return Json(vm);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult RescueStorageQuantProduct(int id)
        {
            var model = ProductModel.IdRescue(id);
            if (model != null)
            {
                return Json(new { OK = true, Result = model.StorageQuant });
            }
            else
            {
                return Json(new { OK = false });
            }
        }

        [HttpPost]
        [Authorize(Roles = "Administrator")]
        [ValidateAntiForgeryToken]
        public JsonResult DeleteProduct(int id)
        {
            return Json(ProductModel.IdDelete(id));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult SaveProduct()
        {
            var result = "OK";
            var message = new List<string>();
            var idSaved = string.Empty;

            var nameImageFile = "";
            HttpPostedFileBase archive = null;
            if (Request.Files.Count > 0)
            {
                archive = Request.Files[0];
                nameImageFile = Guid.NewGuid().ToString() + ".jpg"; //generates random name for product images
            }
            
            var vm = new ProductViewModel()
            {
                Id = (Request.Form["Id"]).ToInt32(),
                Code = Request.Form["Code"],
                Name = Request.Form["Name"],
                CostValue = (Request.Form["CostValue"]).ToDecimal(),
                Price = (Request.Form["Price"]).ToDecimal(),
                StorageQuant = (Request.Form["StorageQuant"]).ToInt32(),
                IdUnitMeasure = (Request.Form["IdUnitMeasure"]).ToInt32(),
                IdGroup = (Request.Form["IdGroup"]).ToInt32(),
                IdBrand = (Request.Form["IdBrand"]).ToInt32(),
                IdProvider = (Request.Form["IdProvider"]).ToInt32(),
                IdStorageLocation = (Request.Form["IdStorageLocation"]).ToInt32(),
                Active = (Request.Form["Active"] == "true"),
                Image = nameImageFile
            };

            var context = new ValidationContext(vm);
            var results = new List<ValidationResult>();
            var valid = Validator.TryValidateObject(vm, context, results);


            if (!valid)
            {
                result = "Warning";
                message = results.Select(x => x.ErrorMessage).ToList();
            }
            else
            {
                var model = new ProductModel()
                {
                    Id = vm.Id,
                    Code = vm.Code,
                    Name = vm.Name,
                    CostValue = vm.CostValue,
                    Price = vm.Price,
                    StorageQuant = vm.StorageQuant,
                    IdUnitMeasure = vm.IdUnitMeasure,
                    IdGroup = vm.IdGroup,
                    IdBrand = vm.IdBrand,
                    IdProvider = vm.IdProvider,
                    IdStorageLocation = vm.IdStorageLocation,
                    Active = vm.Active,
                    Image = vm.Image
                };

                try
                {
                    var nameImageFilePrevious = "";
                    if (model.Id > 0)
                    {
                        nameImageFilePrevious = ProductModel.RescueImageId(model.Id);

                    }

                    var id = model.Savee();
                    if (id > 0)
                    {
                        idSaved = id.ToString();
                        if (!string.IsNullOrEmpty(nameImageFile) && archive != null)
                        {
                            var dir = Server.MapPath("~/Content/Images");
                            var archivepath = Path.Combine(dir, nameImageFile);
                            archive.SaveAs(archivepath);    

                            if (!string.IsNullOrEmpty(nameImageFilePrevious))
                            {
                                var pathPreviousImage = Path.Combine(dir, nameImageFilePrevious);
                                System.IO.File.Delete(pathPreviousImage);
                            }
                        }
                    }
                    else
                    {
                        result = "Error";
                    }
                }


                catch (Exception ex)
                {
                    result = "Error";
                }


            }
            return Json(new { Result = result, Message = message, IdSaved = idSaved });

        }

    }
}

Inventory.Web/Views/RegisterProduct/Index.cshtml
@model List<Inventory.Web.Models.ProductViewModel>
@{
    Layout = "~/Views/Shared/_Register.cshtml";
    ViewBag.Title = "MM Product";
    ViewBag.List = Model;

}

@section Styles{
    <link href="~/Content/bootstrap-select.css" rel="stylesheet" />
    <link href="~/Content/Register/Product.css" rel="stylesheet" />
    <style>
        .dialog > .modal-dialog {
            width: 700px !important;
        }
    </style>
}

@section TitleGrid{
    <th><span class="column-ordenation" data-campo="code">Code</span></th>
    <th><span class="column-ordenation" data-campo="name">Name</span></th>
    <th><span class="column-ordenation" data-campo="storage_quant">Quantity</span></th>
    <th><span class="column-ordenation" data-campo="active">Active</span></th>
    <th>Action</th>
}


@section RegisterInputs{

    <div class="row">
        <div class="col-md-4">
            @Html.Label("txt_code", "Code", new { @class = "control-label" })
            @Html.TextBox("txt_code", null, new { @class = "form-control" })
        </div>

        <div class="col-md-8">
            @Html.Label("txt_name", "Name", new { @class = "control-label" })
            @Html.TextBox("txt_name", null, new { @class = "form-control" })
        </div>
    </div>
    <div class="row">
        <div class="col-md-4">
            @Html.Label("txt_cost_value", "Cost Value", new { @class = "control-label" })
            @Html.TextBox("txt_cost_value", null, new { @class = "form-control" })
        </div>
        <div class="col-md-4">
            @Html.Label("txt_price", "Price", new { @class = "control-label" })
            @Html.TextBox("txt_price", null, new { @class = "form-control" })
        </div>

        <div class="col-md-4">
            @Html.Label("txt_storage_quant", "Storage Quantity", new { @class = "control-label" })
            @Html.TextBox("txt_storage_quant", null, new { @class = "form-control" })
        </div>
    </div>
    <div class="row">
        <div class="col-md-4">
            @Html.Label("ddl_unit_measure", "Unit Measure", new { @class = "control-label" })
            @Html.DropDownList("ddl_unit_measure", new SelectList(ViewBag.UnitsMeasure, "Id", "Name"), new { @class = "form-control" })
        </div>

        <div class="col-md-8">
            @Html.Label("ddl_group", "Group", new { @class = "control-label" })
            @Html.DropDownList("ddl_group", new SelectList(ViewBag.Groups, "Id", "Name"), new { @class = "form-control" })
        </div>
    </div>

    <div class="row">
        <div class="col-md-4">
            @Html.Label("ddl_brand", "Brand", new { @class = "control-label" })
            @Html.DropDownList("ddl_brand", new SelectList(ViewBag.Brands, "Id", "Name"), new { @class = "form-control" })
        </div>

        <div class="col-md-8">
            @Html.Label("ddl_provider", "Provider", new { @class = "control-label" })
            @Html.DropDownList("ddl_provider", new SelectList(ViewBag.Providers, "Id", "Name"), new { @class = "form-control" })
        </div>
    </div>

    <div class="row">
        <div class="col-md-4">
            @Html.Label("ddl_storage_location", "Storage Location", new { @class = "control-label" })
            @Html.DropDownList("ddl_storage_location", new SelectList(ViewBag.StorageLocations, "Id", "Name"), new { @class = "form-control" })
        </div>

        <div class="col-md-8">
            <div class="form-check" style="line-height: 6em; margin-bottom: -2em">
                @Html.CheckBox("cbx_active", new { @class = "form-check-input" })
                @Html.Label("cbx_active", "Active", new { @class = "form-check-label" })

            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            @Html.Label("txt_image", "Image", new { @class = "control-label" })
            @Html.TextBox("txt_image", null, new { @class = "form-control", type = "file", accept = "image/jpg, image/jpeg" })
        </div>

    </div>
    <div id="modal_image" class="invisible2" role="dialog">

    </div>

}

@section Scripts{
    <script src="~/Scripts/bootstrap-select.js"></script>
    <script src="~/Scripts/jquery.mask.min.js"></script>

    <script>
        var page_title = '@ViewBag.Title';
        var url_edit = '@Url.Action("RescueProduct", "RegisterProduct")';
        var url_delete = '@Url.Action("DeleteProduct", "RegisterProduct")';
        var url_save = '@Url.Action("SaveProduct", "RegisterProduct")';
        var url_page_click = '@Url.Action("ProductPage", "RegisterProduct")';
        var url_filter = '@Url.Action("ProductPage", "RegisterProduct")';
        var url_len_page_change = '@Url.Action("ProductPage", "RegisterProduct")';
        var liness = [];

    @{
        var lines = 0;
        foreach (var item in Model)
        {
            lines++;
            if (lines <= ViewBag.QuantMaxLinesPerPage)
            {
                     @:liness.push(@Html.Raw(Json.Encode(item)));
            }
            else
            {
                break;
            }
        }
    }

    </script>
    <script id="template-grid" type="x-template-mustache">
        <tr data-id="{{ Id }}" data-image="{{ Image }}">
            <td>{{ Code }}</td>
            <td>{{ Name }}</td>
            <td>{{ StorageQuant }}</td>
            <td>{{ #Active }}YES{{ /Active }}{{ ^Active }}NO{{ /Active }}</td>
            <td>
                <a class="btn btn-default btn-show-image" role="button"><i class="glyphicon glyphicon-picture"></i></a>
                <a class="btn btn-primary btn-edit" role="button"><i class="glyphicon glyphicon-pencil"></i> Edit</a>
                <a class="btn btn-danger btn-delete" role="button"><i class="glyphicon glyphicon-trash"></i> Delete</a>
            </td>
        </tr>
    </script>

    <script id="template-image" type="x-template-mustache">
        <fieldset>
            <div class="row">
                <div class="col-md-12">
                    <img src="/Content/Images/{{ Image }}" />
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="form-group">
                        <div class="modal-footer">
                            <a id="btn_exit_image" class="btn btn-default" role="button" data-dismiss="modal">
                                <i class="glyphicon glyphicon-remove"></i> Sair
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </fieldset>
    </script>
    <script src="~/Scripts/Register/Product.js"></script>
}