Inventory.Web/Controllers/GraphsController.cs
using Inventory.Web.Models;
using System;
using System.Collections.Generic;
using System.Web.Mvc;

namespace Inventory.Web.Controllers
{
    public class GraphsController : BaseController
    {
        [Authorize]
        public ActionResult MontlyLostProducts()
        {

            var month = DateTime.Today.Month;
            var year = DateTime.Today.Year;
            var dayquantity = DateTime.DaysInMonth(year, month);

            var days = new List<int>();
            var lost = new List<int>();
            for (var day = 1; day <= dayquantity; day++)
            {
                days.Add(day);
                lost.Add(0);
            }

            foreach (var lostBd in ProductModel.MonthlyLost(month, year))
            {
                lost[lostBd.Day - 1] = lostBd.Quant;
            }


            ViewBag.Days = days;
            ViewBag.Month = month;
            ViewBag.Year = year;
            ViewBag.Lost = lost;

            return View();
        }
        [Authorize]
        public ActionResult MontlyEntryOutput()
        {
            return View();
        }
    }
}

Inventory.Web/Controllers/Register/RegisterCityController.cs
using Inventory.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;


namespace Inventory.Web.Controllers
{
    [Authorize(Roles = "Administrator, Operator")]

    public class RegisterCityController : BaseController
    {
        private const int _quantMaxLinesPerPage = 5;
        private const int ActualPage = 1;


        public ActionResult Index()
        {
            ViewBag.ListLenPage = new SelectList(new int[] { _quantMaxLinesPerPage, 10, 15, 20 }, _quantMaxLinesPerPage);
            ViewBag.QuantMaxLinesPerPage = _quantMaxLinesPerPage;
            ViewBag.ActualPage = 1;

            var list = CityModel.RescueList(ActualPage, _quantMaxLinesPerPage);
            var quant = CityModel.RescueQuantity();

            var difQuantPages = (quant % ViewBag.QuantMaxLinesPerPage) > 0 ? 1 : 0;
            ViewBag.QuantPages = (quant / ViewBag.QuantMaxLinesPerPage) + difQuantPages;
            ViewBag.Countries = Mapper.Map<List<CountryViewModel>>(CountryModel.RescueList());
            ViewBag.Countries.Insert(0, new CountryViewModel { Id = -1, Name = "-- Not Selected --" });


            return View(list);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult CityPage(int page, int lenPage, string filter, string order)
        {
            var list = CityModel.RescueList(page, lenPage, filter, order);

            return Json(list);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult RescueCity(int id)
        {
            var vm = CityModel.IdRescue(id);
            return Json(vm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult RescueCitiesbyProvinces(int idProvince)
        {
            var list = CityModel.RescueList(idProvince: idProvince);
            list.Insert(0, new CityViewModel { Id = -1, Name = "-- Not Selected --" });
            return Json(list);
        }


        [HttpPost]
        [Authorize(Roles = "Administrator")]
        [ValidateAntiForgeryToken]
        public JsonResult DeleteCity(int id)
        {
            return Json(CityModel.IdDelete(id));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult SaveCity(CityViewModel model)
        {
            var result = "OK";
            var message = new List<string>();
            var idSaved = string.Empty;
            if (!ModelState.IsValid)
            {
                result = "Warning";
                message = ModelState.Values.SelectMany(x => x.Errors).Select(x => x.ErrorMessage).ToList();
            }
            else
            {
                try
                {
                    var vm = Mapper.Map<CityModel>(model);
                    var id = vm.Savee();
                    if (id > 0)
                    {
                        idSaved = id.ToString();
                    }
                    else
                    {
                        result = "Error";
                    }
                }


                catch (Exception ex)
                {
                    result = "Error";
                }


            }
            return Json(new { Result = result, Message = message, IdSaved = idSaved });

        }
    }
}

Inventory.Web/Controllers/Register/RegisterCountryController.cs
using Inventory.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Inventory.Web.Controllers.Register
{
    [Authorize(Roles = "Administrator, Operator")]
    public class RegisterCountryController : BaseController
    {
        private const int _quantMaxLinesPerPage = 5;
        private const int ActualPage = 1;


        public ActionResult Index()
        {
            ViewBag.ListLenPage = new SelectList(new int[] { _quantMaxLinesPerPage, 10, 15, 20 }, _quantMaxLinesPerPage);
            ViewBag.QuantMaxLinesPerPage = _quantMaxLinesPerPage;
            ViewBag.ActualPage = 1;

            //var list = Mapper.Map<List<CountryViewModel>>(CountryModel.RescueList(ViewBag.ActualPage, _quantMaxLinesPerPage));
            var list = Mapper.Map<List<CountryViewModel>>(CountryModel.RescueList(ActualPage,_quantMaxLinesPerPage));
            var quant = CountryModel.RescueQuantity();

            var difQuantPages = (quant % ViewBag.QuantMaxLinesPerPage) > 0 ? 1 : 0;
            ViewBag.QuantPages = (quant / ViewBag.QuantMaxLinesPerPage) + difQuantPages;

            return View(list);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult CountryPage(int page, int lenPage, string filter, string order)
        {
            var list = Mapper.Map<List<CountryViewModel>>(CountryModel.RescueList(page, lenPage, filter, order));

            return Json(list);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult RescueCountry(int id)
        {
            // throw new Exception(); forcando erro
            var vm = Mapper.Map<CountryViewModel>(CountryModel.IdRescue(id));
            return Json(vm);
        }

        [HttpPost]
        [Authorize(Roles = "Administrator")]
        [ValidateAntiForgeryToken]
        public JsonResult DeleteCountry(int id)
        {
            return Json(CountryModel.IdDelete(id));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult SaveCountry(CountryViewModel model)
        {
            var result = "OK";
            var message = new List<string>();
            var idSaved = string.Empty;
            if (!ModelState.IsValid)
            {
                result = "Warning";
                message = ModelState.Values.SelectMany(x => x.Errors).Select(x => x.ErrorMessage).ToList();
            }
            else
            {
                try
                {
                    var vm = Mapper.Map<CountryModel>(model);
                    var id = vm.Savee();
                    if (id > 0)
                    {
                        idSaved = id.ToString();
                    }
                    else
                    {
                        result = "Error";
                    }
                }


                catch (Exception ex)
                {
                    result = "Error";
                }


            }
            return Json(new { Result = result, Message = message, IdSaved = idSaved });

        }



    }
}

Inventory.Web/Controllers/Register/RegisterNewEmployeeController.cs
using Inventory.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace Inventory.Web.Controllers
{
    [Authorize(Roles = "Administrator, Operator")]
    public class RegisterNewEmployeeController : BaseController
    {
        public ActionResult FirstTab()
        {
            return PartialView("_FirstTab");
        }

        public ActionResult SecondTab()
        {
            return PartialView("_SecondTab");
        }
        public ActionResult ThirdTab()
        {
            return PartialView("_ThirdTab");
        }
        public ActionResult FourthTab()
        {
            return PartialView("_FourthTab");
        }
        public ActionResult FifthTab()
        {
            return PartialView("_FifthTab");
        }
        public ActionResult FifthTab_1()
        {
            return PartialView("_FifthTab_1");
        }
        public ActionResult FifthTab_2()
        {
            return PartialView("_FifthTab_2");
        }
        public ActionResult FifthTab_3()
        {
            return PartialView("_FifthTab_3");
        }

        public ActionResult SixtyTab()
        {
            return PartialView("_SixtyTab");
        }

        private const int _quantMaxLinesPerPage = 5;
        private const int ActualPage = 1;

        public ActionResult Index()
        {
            ViewBag.ListLenPage = new SelectList(new int[] { _quantMaxLinesPerPage, 10, 15, 20 }, _quantMaxLinesPerPage);
            ViewBag.QuantMaxLinesPerPage = _quantMaxLinesPerPage;
            ViewBag.ActualPage = 1;

            //var list = Mapper.Map<List<EmployeeViewModel>>(EmployeeModel.RescueList(ActualPage, _quantMaxLinesPerPage));
            var list = Mapper.Map<List<EmployeeViewModel>>(EmployeeModel.RescueList(ActualPage, _quantMaxLinesPerPage));

            var quant = EmployeeModel.RescueQuantity();

            var difQuantPages = (quant % ViewBag.QuantMaxLinesPerPage) > 0 ? 1 : 0;
            ViewBag.QuantPages = (quant / ViewBag.QuantMaxLinesPerPage) + difQuantPages;


            List<SelectListItem> payrollinfo = new List<SelectListItem>(){
                new SelectListItem { Text = "", Value = "Empty" },
                new SelectListItem { Text = "Salary", Value = "Salary" },
                new SelectListItem { Text = "Sick Salary", Value = "Sick Salary" },
                new SelectListItem { Text = "Vacation Salary", Value = "Vacation Salary" },
                new SelectListItem { Text = "Overtime Rate", Value = "Overtime Rate" },
                new SelectListItem { Text = "Regular Pay", Value = "Regular Pay" },
                new SelectListItem { Text = "Sick Hourly", Value = "Sick Hourly" },
                new SelectListItem { Text = "Vacation Hourly", Value = "Vacation Hourly" },
                new SelectListItem { Text = "Bonus", Value = "Bonus" },


            };
            ViewBag.PayrollInfo = payrollinfo;




            List<SelectListItem> payrollfrequency = new List<SelectListItem>(){
                new SelectListItem { Text = "Weekly", Value = "Weekly" },
                new SelectListItem { Text = "Biweekly", Value = "Biweekly" },
                new SelectListItem { Text = "Monthly", Value = "Monthly" },
                new SelectListItem { Text = "Other", Value = "Other" },


            };
            ViewBag.PayrollFrequency = payrollfrequency;


            List<SelectListItem> gender = new List<SelectListItem>(){
                new SelectListItem { Text = "Male", Value = "0" },
                new SelectListItem { Text = "Female", Value = "1" },
                new SelectListItem { Text = "Other", Value = "2" },

            };
            ViewBag.Gender = gender;


            List<SelectListItem> marital = new List<SelectListItem>(){
                new SelectListItem { Text = "Single", Value = "Single" },
                new SelectListItem { Text = "Married", Value = "Married" },
                new SelectListItem { Text = "Widowed", Value = "Widowed" },
                new SelectListItem { Text = "Divorced", Value = "Divorced" },

            };
            ViewBag.Marital = marital;


            List<SelectListItem> ethnicity = new List<SelectListItem>(){
                new SelectListItem { Text = "White", Value = "White" },
                new SelectListItem { Text = "Asian", Value = "Asian" },
                new SelectListItem { Text = "African American", Value = "African American" },
                new SelectListItem { Text = "Hispanic", Value = "Hispanic" },
                new SelectListItem { Text = "Other Pacific Islander", Value = "Other Pacific Islander" },
                new SelectListItem { Text = "American Indian", Value = "American Indian" },


            };
            ViewBag.Ethnicity = ethnicity;

            List<SelectListItem> yesno = new List<SelectListItem>(){
                new SelectListItem { Text = "Yes", Value = "0" },
                new SelectListItem { Text = "No", Value = "1" },

            };
            ViewBag.YesNo = yesno;

            return View(list);
        }



        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult EmployeePage(int page, int lenPage, string filter, string order)
        {
            var list = Mapper.Map<List<EmployeeViewModel>>(EmployeeModel.RescueList(page, lenPage, filter, order));

            return Json(list);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult RescueEmployee(int id)
        {
            var vm = Mapper.Map<EmployeeViewModel>(EmployeeModel.IdRescue(id));

            //added
            //string json = JsonSerializer.Serialize(vm.DateBirth);

            //added

            return Json(vm);
        }

        [HttpPost]
        [Authorize(Roles = "Administrator")]
        [ValidateAntiForgeryToken]
        public JsonResult DeleteEmployee(int id)
        {
            return Json(EmployeeModel.IdDelete(id));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult SaveEmployee(EmployeeViewModel model)
        {
            var result = "OK";
            var message = new List<string>();
            var idSaved = string.Empty;
            if (!ModelState.IsValid)
            {
                result = "Warning";
                message = ModelState.Values.SelectMany(x => x.Errors).Select(x => x.ErrorMessage).ToList();
            }
            else
            {
                try
                {
                    var vm = Mapper.Map<EmployeeModel>(model);
                    var id = vm.Savee();
                    if (id > 0)
                    {
                        idSaved = id.ToString();
                    }
                    else
                    {
                        result = "Error";
                    }
                }


                catch (Exception ex)
                {
                    result = "Error";
                }


                //        var vm = new EmployeeViewModel()
                //    {
                //        Id = (Request.Form["Id"]).ToInt32(),
                //        LegalName = Request.Form["LegalName"],
                //        LegalSurname = Request.Form["LegalSurname"],
                //        //EmployeeType = (Request.Form["EmployeeType"]).ToInt32(),
                //        PrintName = Request.Form["PrintName"],
                //        Ssn = (Request.Form["Ssn"]).ToInt32(),
                //        Gender = (Request.Form["Gender"]).ToInt32(),
                //        //DateBirth = DateTime.Parse(Request.Form["DateBirth"]),
                //        MaritalStatus = Request.Form["MaritalStatus"],
                //        UsCitizen = (Request.Form["UsCitizen"]).ToInt32(),
                //        Ethnicity = Request.Form["Ethnicity"],
                //        Disability = (Request.Form["Disability"]).ToInt32(),
                //        DisabilityDescription = Request.Form["DisabilityDescription"],
                //        I9Form = (Request.Form["I9Form"]).ToInt32(),
                //        //WorkExpires = DateTime.Parse(Request.Form["WorkExpires"]), 
                //        UsVeteran = (Request.Form["UsVeteran"]).ToInt32(),
                //        VeteranStatus = Request.Form["VeteranStatus"],

                //        Address1 = Request.Form["Address1"],
                //        Address2 = Request.Form["Address2"],
                //        City = Request.Form["City"],
                //        StateProvince = Request.Form["StateProvince"],
                //        PostalCode = Request.Form["PostalCode"],
                //        PhoneNumber = Request.Form["PhoneNumber"],
                //        MobileNumber = Request.Form["MobileNumber"],
                //        Email = Request.Form["Email"],
                //        ContactName1 = Request.Form["ContactName1"],
                //        ContactPhone1 = Request.Form["ContactPhone1"],
                //        ContactRelation1 = Request.Form["ContactRelation1"],
                //        ContactName2 = Request.Form["ContactName2"],
                //        ContactPhone2 = Request.Form["ContactPhone2"],
                //        ContactRelation2 = Request.Form["ContactRelation2"],

                //        Active = (Request.Form["Active"] == "true"),


                //};

                //    var context = new ValidationContext(vm);
                //    var results = new List<ValidationResult>();
                //    var valid = Validator.TryValidateObject(vm, context, results);


                //    if (!valid)
                //    {
                //        result = "Warning";
                //        message = results.Select(x => x.ErrorMessage).ToList();
                //    }
                //    else
                //    {
                //        var model = new EmployeeModel()
                //        {

Inventory.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Home Service Solutions - Material Management</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="~/Content/sweetalert2.min.css" rel="stylesheet" />
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Home Service Solutions", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse menu_mm">

                @if (Request.IsAuthenticated && ViewBag.Title.Contains("MM"))
                {
                    <ul class="nav navbar-nav">
                        <li>
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                Register
                                <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink("Products Group", "Index", "RegisterProductGroup")</li>
                                <li>@Html.ActionLink("Products Brand", "Index", "RegisterProductBrand")</li>
                                <li>@Html.ActionLink("Storage Locations", "Index", "RegisterStorageLocation")</li>
                                <li>@Html.ActionLink("Units of Measure", "Index", "RegisterUnitMeasure")</li>
                                <li>@Html.ActionLink("Products", "Index", "RegisterProduct")</li>
                                <li class="nav-divider"></li>
                                <li>@Html.ActionLink("Country", "Index", "RegisterCountry")</li>
                                <li>@Html.ActionLink("Province", "Index", "RegisterProvince")</li>
                                <li>@Html.ActionLink("City", "Index", "RegisterCity")</li>
                                <li>@Html.ActionLink("Providers", "Index", "RegisterProvider")</li>
                                @*<li class="nav-divider"></li>
                        <li>@Html.ActionLink("Register Role", "Index", "RegisterRole")</li>
                        <li>@Html.ActionLink("Users", "Index", "RegisterUser")</li>*@
                            </ul>
                        </li>
                        <li>
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                Operations
                                <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink("Product Entry", "Index", "OperProductEntry")</li>
                                <li>@Html.ActionLink("Product Output", "Index", "OperProductOutput")</li>
                                @*<li>@Html.ActionLink("Product Loss", "Index", "OperEntryProductLoss")</li>*@
                                <li>@Html.ActionLink("Stock Inventory", "Index", "OperStockInventory")</li>
                            </ul>
                        </li>
                        <li>
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                Reports
                                <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink("Stock Position", "Index", "ReportStockPosition", null, new { target = "_blank" })</li>
                                <li>@Html.ActionLink("Product Entry", "Index", "ReportProductEntry", null, new { target = "_blank" })</li>
                                <li>@Html.ActionLink("Resupply", "Filter", "ReportResupply")</li>
                                <li>@Html.ActionLink("Product Loss", "Index", "OperEntryProductLoss")</li>

                            </ul>
                        </li>
                        <li>
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                Graphs
                                <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink("Monthly Lost Products", "MontlyLostProducts", "Graphs")</li>
                                <li>@Html.ActionLink("Monthly Entry vs Output", "MontlyEntryOutput", "Graphs")</li>
                            </ul>
                        </li>

                    </ul>
                    using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoffForm" }))
                    {

                        <ul class="nav navbar-nav navbar-right">
                            <li>@Html.ActionLink("About", "About", "Home")</li>
                            <li>
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                    Hi @User.Identity.Name
                                    <span class="caret"></span>
                                </a>
                                <ul class="dropdown-menu">
                                    <li>@Html.ActionLink("Change Password", "ChangeUserPassword", "Account")</li>
                                </ul>
                            </li>

                            <li><a href="javascript:document.getElementById('logoffForm').submit()">LogOff</a></li>
                        </ul>
                    }
                }
                else if (Request.IsAuthenticated && ViewBag.Title.Contains("HR"))
                {
            <ul class="nav navbar-nav">
                <li>
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        Register
                        <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li>@Html.ActionLink("New Employee", "Index", "RegisterNewEmployee")</li>
                        <li>@Html.ActionLink("New Vendor", "Index", "RegisterNewVendor")</li>
                    </ul>
                </li>
                <li>
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        Manage Employee Info
                        <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li>@Html.ActionLink("Add / Edit Sales Rep", "Index", "AddEditSalesRep")</li>
                        <li>@Html.ActionLink("Change New Employee Defaut Settings", "Index", "EditDefautSettings")</li>
                    </ul>
                </li>
                <li>
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        Print
                        <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li>@Html.ActionLink("Print Paychecks", "Index", "PrintPaycheks")</li>
                        <li>@Html.ActionLink("Print / Send Paystubs", "Index", "PrintSendPaystubs")</li>
                        <li class="nav-divider"></li>
                        <li>@Html.ActionLink("Employee List", "Index", "EmployeeList")</li>
                        <li>@Html.ActionLink("Employee Information", "Index", "EmployeeInformation")</li>
                        <li>@Html.ActionLink("Employee Transaction List", "Index", "EmployeeTransactionList")</li>


                    </ul>
                </li>
                <li>
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        Enter Time
                        <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li>@Html.ActionLink("Use Weekly Timesheet", "Index", "WeeklyTimesheet")</li>
                        <li>@Html.ActionLink("Time / Enter Single Activity", "Index", "TimeEnterSingleActivity")</li>
                    </ul>
                </li>
                <li>
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        Excel
                        <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li>@Html.ActionLink("Export Employee List", "Index", "ExcelExportEmployeeList")</li>
                        <li>@Html.ActionLink("Export Transactions", "Index", "ExcelExportTransactions")</li>
                        <li>@Html.ActionLink("Summarize Payroll Data in Execel", "Index", "ExcelSummarizePayroll")</li>

                    </ul>
                </li>

                <li>
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        Word
                        <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li>@Html.ActionLink("Prepare Letter to Scott Walker", "Index", "PrepareLetter")</li>
                        <li>@Html.ActionLink("Prepare Employee Letters", "Index", "PrepareEmployeeLetters")</li>
                        <li>@Html.ActionLink("Customize Letter Templates", "Index", "CustomizeLetterTemplates")</li>

                    </ul>
                </li>
            </ul>
                    using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoffForm" }))
                    {

                        <ul class="nav navbar-nav navbar-right">
                            <li>@Html.ActionLink("About", "About", "Home")</li>
                            <li>
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                    Hi @User.Identity.Name
                                    <span class="caret"></span>
                                </a>
                                <ul class="dropdown-menu">
                                    <li>@Html.ActionLink("Change Password", "ChangeUserPassword", "Account")</li>
                                </ul>
                            </li>

                            <li><a href="javascript:document.getElementById('logoffForm').submit()">LogOff</a></li>
                        </ul>
                    }
                }
                else if (Request.IsAuthenticated && ViewBag.Title.Contains("CRM"))
                {

                }
                else if (Request.IsAuthenticated)
                {
                    <ul class="nav navbar-nav">
                        <li>
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                Register Users / Role
                                <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink("Register Role", "Index", "RegisterRole")</li>
                                <li>@Html.ActionLink("Users", "Index", "RegisterUser")</li>
                            </ul>
                        </li>
                    </ul>
                    using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoffForm" }))
                    {
                        <ul class="nav navbar-nav navbar-right">
                            <li>@Html.ActionLink("About", "About", "Home")</li>
                            <li>
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                    Hi @User.Identity.Name
                                    <span class="caret"></span>
                                </a>
                                <ul class="dropdown-menu">
                                    <li>@Html.ActionLink("Change Password", "ChangeUserPassword", "Account")</li>
                                </ul>
                            </li>

                            <li><a href="javascript:document.getElementById('logoffForm').submit()">LogOff</a></li>
                        </ul>
                    }
                }

                else
                {
                    <ul class="nav navbar-nav navbar-right">
                        <li>@Html.ActionLink("Login", "Login", "Account")</li>

                    </ul>
                }
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year -  Home Service Solutions</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <script src="~/Scripts/sweetalert2.min.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>