Inventory.Web/Controllers/HRController.cs
using System.Web.Mvc;

namespace Inventory.Web.Controllers
{
    public class HRController : BaseController
    {
        [Authorize]
        public ActionResult Index()
        {
            return View();
        }
    }
}

Inventory.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Inventory.Web.Controllers
{
    public class HomeController : BaseController
    {
        [Authorize]
        public ActionResult Index()
        {
            return View();
        }
        [Authorize]
        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }
        [Authorize]
        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

    }
}

Inventory.Web/Controllers/MMController.cs
using System.Web.Mvc;

namespace Inventory.Web.Controllers
{
    public class MMController : BaseController
    {
        [Authorize]
        public ActionResult Index()
        {
            return View();
        }
    }
}

Inventory.Web/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<div class="row">
    <div class="col-md-6">
        <h2>@ViewBag.Title Home Service Solutions.</h2>
        <p>
            Welcome to Home Service Solutions Intranet, your all in one Home Service company.
            <br />
            We know how important your home is, it's just as important to us!
            <br />
            If you haven't used our services in the past you should know we are a customer first company and bringing you happiness is our #1 mission.
            <br />
            We truly stand behind that.
            <br /><br />
            We want to be your home maintenance company that takes care of you and your home as long as you need it.
            <br /><br />
            If you have any questions, or are ready to book your next service, we would love the opportunity to go above and beyond for you and your homes needs.
            <br />
            Relax, we've got it.
        </p>
    </div>

</div>

Inventory.Web/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home";
}

<div class="row module_btn">
    <div class="col-md-4">
        <ul>
            <li id="mm_module_btn">
                @Html.ActionLink("Material Management", "Index", "MM")
            </li>
        </ul>
    </div>
    <div class="col-md-4">
        <ul>
            <li id="mm_module_btn">
                @Html.ActionLink("Human Resource", "Index", "HR")
            </li>
        </ul>
    </div>
    <div class="col-md-4">
        <ul>
            <li id="mm_module_btn">
                @Html.ActionLink("CRM", "Index", "CRM")
            </li>
        </ul>
    </div>
</div>